accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
]

bae/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from .views import index, blog, post, search, post_by_category, post_by_tags

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('blog/', blog, name='post-list'),
    path('post/<id>/', post, name='post-detail'),
    path('category/<name>/', post_by_category, name = 'post_by_category'),
    path('tags/<name>/', post_by_tags, name = 'post_by_tags'),
    path('search/', search, name='search'),
    path('accounts/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
# Create your models here.

class Tags(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField(default='', blank=True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('post_by_tags', kwargs={
            'name':self.title
        })


class Category(models.Model):
    title = models.CharField(max_length=20)
    slug = models.SlugField(default='', blank=True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('post_by_category', kwargs={
            'name':self.title
        })
#    class Meta:
#        app_label = 'featured'
#        managed = True

class Post(models.Model):
    title = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=5000)
    content = RichTextUploadingField()
    author = models.CharField(max_length=100)
    thumbnail = models.ImageField()
    categories = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tags)
    slug = models.SlugField(default='', blank=True)
    featured = models.BooleanField()
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={
            'id': self.id
        })

    def get_year(self):
        return self.timestamp.strftime("%Y")

    def get_month(self):
        return self.timestamp.strftime("%B")

    def get_day(self):
        return self.timestamp.strftime("%d")



    #class Meta:
    #    app_label = 'post'
    #    managed = True

post/forms.py
from django import forms
from .models import Post
from ckeditor_uploader.widgets import CKEditorWidget, CKEditorUploadingWidget


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Post
        fields = ('title', 'content', 'thumbnail',
        'categories', 'featured')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # Sign the user the fuck up
            return render(request, 'accounts/login.html')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            return render(request, 'admin_index.html')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

bae/views.py
from django.shortcuts import render
from post.models import Post, Category, Tags
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Q
from next_prev import next_in_order, prev_in_order


def post_by_category(request, name):
        #category = Category.objects.get(slug=category_slug)
        posts = Post.objects.filter(categories__title=name)
        paginator = Paginator(posts, 4)
        page_request_var = 'page'
        page = request.GET.get(page_request_var)
        try:
            paginated_queryset = paginator.page(page)
        except PageNotAnInteger:
            paginated_queryset = paginator.page(1)
        except EmptyPage:
            paginated_queryset = paginator.page(paginator.num_pages)
        context = {
            'posts': posts,
            'name': name,
            'page_request_var': page_request_var,
            'queryset': paginated_queryset
        }
        return render(request, 'category.html', context)


def post_by_tags(request, name):
    posts = Post.objects.filter(tags__title=name)
    paginator = Paginator(posts, 4)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        paginated_queryset = paginator.page(page)
    except PageNotAnInteger:
        paginated_queryset = paginator.page(1)
    except EmptyPage:
        paginated_queryset = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
        'name': name,
        'page_request_var': page_request_var,
        'queryset': paginated_queryset
    }
    return render(request, 'tags.html', context)


def search(request):
    queryset = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query)
        ).distinct()
    context = {
    'queryset': queryset
    }
    return render(request, 'search_results.html', context)

def index(request):
    featured = Post.objects.filter(featured=True)[1:4]
    latest = Post.objects.order_by('-timestamp')[0:3]
    context = {
        'object_list': featured,
        'latest': latest
    }
    return render(request, 'index.html', context)


def get_category_count():
    queryset = Post.objects.values('categories__title').annotate(Count('categories__title'))
    print (queryset)
    return queryset


def blog(request):
    category_count = get_category_count()
    most_recent = Post.objects.order_by('-timestamp')[:3]
    post_list= Post.objects.all()
    paginator = Paginator(post_list, 4)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        paginated_queryset = paginator.page(page)
    except PageNotAnInteger:
        paginated_queryset = paginator.page(1)
    except EmptyPage:
        paginated_queryset = paginator.page(paginator.num_pages)
    context = {
        'queryset': paginated_queryset,
        'most_recent': most_recent,
        'page_request_var': page_request_var,
        'category_count': category_count
    }
    return render(request, 'blog.html', context)

def post(request, id):
    post = Post.objects.get(id=id)
    categ = Category.objects.all
    category_count = get_category_count()
    most_recent = Post.objects.order_by('-timestamp')[:3]
    context = {
    'post': post,
    'most_recent': most_recent,
    'category_count': category_count,
    'categ': categ
    }
    return render(request, 'post.html', context)

post/views.py
from django.shortcuts import render
from django.contrib.auth import views
from django.urls import path
from .forms import CommentForm, PostForm
from .models import Post, Author, PostView

urlpatterns = [

]
# Create your views here.
class PostCreateView(CreateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        return context

    def form_valid(self, form):
        form.save()
        return redirect(reverse("post-detail", kwargs={
            'pk': form.instance.pk
        }))


def post_create(request):
    title = 'Create'
    form = PostForm(request.POST or None, request.FILES or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect(reverse("post-detail", kwargs={
                'id': form.instance.id
            }))
    context = {
        'title': title,
        'form': form
    }
    return render(request, "post_create.html", context)

accounts/templates/accounts/login.html
{% extends 'base.html '%}

{% block content %}
  <h1>Login</h1>
  <form class="site-form" action ="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Log In ">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html '%}

{% block content %}
  <h1>SignUp</h1>
  <form class="site-form" action ="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
    </form>
{% endblock %}

templates/admin_base.html
<!DOCTYPE html>
<html>

{% include 'head.html' %}

<body>
{% include 'admin_header.html' %}
{% block content %}

{% endblock content%}
{% include 'footer.html' %}
{% include 'scripts.html' %}
</html>

templates/admin_header.html
<header class="header">
  <!-- Main Navbar-->
  <nav class="navbar navbar-expand-lg">
    <div class="search-area">
      <div class="search-area-inner d-flex align-items-center justify-content-center">
        <div class="close-btn"><i class="icon-close"></i></div>
        <div class="row d-flex justify-content-center">
          <div class="col-md-8">
            <form action="#">
              <div class="form-group">
                <input type="search" name="search" id="search" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search-1"></i></button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <!-- Navbar Brand -->
      <div class="navbar-header d-flex align-items-center justify-content-between">
        <!-- Navbar Brand --><a href="admin_index.html" class="navbar-brand">The Darkest White</a>
        <!-- Toggle Button-->
        <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
      </div>
      <!-- Navbar Menu -->
      <div id="navbarcollapse" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><a href="/" class="nav-link ">Home</a>
          </li>
          <li class="nav-item"><a href="/blog" class="nav-link">Create a Post</a>
          </li>
          <li class="nav-item"><a href="/post" class="nav-link ">View/Modify Previous Posts</a>
        </ul>
     </div>
    </div>
  </nav>
</header>

templates/admin_index.html
{% extends 'admin_base.html' %}
{% load static %}
{% block content %}
  <h1>Welcome, LC operative.</h1>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>

{% include 'head.html' %}

<body>
{% include 'header.html' %}
{% block content %}

{% endblock content%}
{% include 'footer.html' %}
{% include 'scripts.html' %}
</html>   

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8">
          <div class="container">
            <div class="row">
              <!-- post -->
              {% for post in queryset %}
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{{ post.get_absolute_url }}"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">{{ post.get_day }} {{ post.get_month }} | {{ post.get_year }}</div>
                    {% for cat in post.categories.all %}
                    <div class="category"><a href="{{ cat.get_absolute_}}">{{ cat.title }}</a></div>
                    {% endfor %}
                  </div><a href="{{ post.get_absolute_url }}">
                    <h3 class="h4">{{ post.title }}</h3></a>
                  <p class="text-muted">{{ post.description }}</p>
                  <footer class="post-footer d-flex align-items-center">
                    <a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="title"><span>{{ post.author }}</span></div></a>
                    <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                  </footer>
                </div>
              </div>
              {% endfor %}
            </div>
            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if queryset.has_previous %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.number }}" class="page-link active">{{ queryset.number }}</a></li>
                {% if queryset.has_next %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </main>
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="{% url 'search' %}" class="search-form">
              <div class="form-group">
                <input type="text" name="q" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
            <div class="blog-posts">
              {% for post in most_recent %}
              <a href="{{ post.get_absolute_url }}">
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ post.title }}</strong>
                    <div class="d-flex align-items-center">
                    </div>
                  </div>
                </div></a>
              {% endfor %}
          </div>
          </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">Categories</h3>
            </header>
            {% for cat in category_count %}
            <div class="item d-flex justify-content-between"><a href="#">{{ cat.categories__title}}</a><span>{{ cat.categories__title__count }}</span></div>
            {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
        <!--  <div class="widget tags">
            <header>
              <h3 class="h6">Tags</h3>
            </header>
            <ul class="list-inline">
              <li class="list-inline-item"><a href="#" class="tag">#Business</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Technology</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Fashion</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Sports</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Economy</a></li>
            </ul>
          </div> -->
        </aside>
      </div>
    </div>


{% endblock content %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<main class="posts-listing ">
  <div class="container">
    <div class="row">
      <div class="heading">
      <h2>Here's what we found for posts under category {{ name }}.</h2>
      </div>
      <!-- post -->
      {% for post in posts %}
      <div class="post col-xl-6">
        <div class="post-thumbnail"><a href="{{ post.get_absolute_url }}"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
        <div class="post-details">
          <div class="post-meta d-flex justify-content-between">
            <div class="date meta-last">20 May | 2016</div>
            {% for cat in post.categories.all %}
            <div class="category"><a href="#">{{ cat.title }}</a></div>
            {% endfor %}
          </div><a href="{{ post.get_absolute_url }}">
            <h3 class="h4">{{ post.title }}</h3></a>
          <p class="text-muted">{{ post.description }}</p>
          <footer class="post-footer d-flex align-items-center">
            <a href="#" class="author d-flex align-items-center flex-wrap">
              <div class="title"><span>{{ post.author }}</span></div></a>
            <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
          </footer>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- Pagination -->
    <nav aria-label="Page navigation example">
      <ul class="pagination pagination-template d-flex justify-content-center">
        {% if posts.has_previous %}
        <li class="page-item"><a href="?{{ page_request_var }}={{ posts.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
        {% endif %}
        <li class="page-item"><a href="?{{ page_request_var }}={{ posts.number }}" class="page-link active">{{ queryset.number }}</a></li>
        {% if queryset.has_next %}
        <li class="page-item"><a href="?{{ page_request_var }}={{ posts.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
        {% endif %}
      </ul>
    </nav>
  </div>
</main>

{% endblock content %}

templates/footer.html
<!-- Page Footer-->
<footer class="main-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="logo">
          <h6 class="text-white">The Darkest White</h6>
        </div>
        <div class="contact-details">
          <p>Mahatma Gandhi Road, NIT Durgapur, Durgapur</p>
          <p>Phone: (020) 123 456 789</p>
          <p>Email: <a href="mailto:lcnitd@gmail.com">lcnitd@gmail.com</a></p>
          <ul class="social-menu">
            <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-youtube"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
          </ul>
        </div>
      </div>
    <!--  <div class="col-md-4">
        <div class="menus d-flex">
          <ul class="list-unstyled">
            <li> <a href="#">My Account</a></li>
            <li> <a href="#">Add Listing</a></li>
            <li> <a href="#">Pricing</a></li>
            <li> <a href="#">Privacy &amp; Policy</a></li>
          </ul>
          <ul class="list-unstyled">
            <li> <a href="#">Our Partners</a></li>
            <li> <a href="#">FAQ</a></li>
            <li> <a href="#">How It Works</a></li>
            <li> <a href="#">Contact</a></li>
          </ul>
        </div>
      </div> -->
    <!--  <div class="col-md-4">
        <div class="latest-posts"><a href="#">
            <div class="post d-flex align-items-center">
              <div class="image"><img src="img/small-thumbnail-1.jpg" alt="..." class="img-fluid"></div>
              <div class="title"><strong>Hotels for all budgets</strong><span class="date last-meta">October 26, 2016</span></div>
            </div></a><a href="#">
            <div class="post d-flex align-items-center">
              <div class="image"><img src="img/small-thumbnail-2.jpg" alt="..." class="img-fluid"></div>
              <div class="title"><strong>Great street atrs in London</strong><span class="date last-meta">October 26, 2016</span></div>
            </div></a><a href="#">
            <div class="post d-flex align-items-center">
              <div class="image"><img src="img/small-thumbnail-3.jpg" alt="..." class="img-fluid"></div>
              <div class="title"><strong>Best coffee shops in Sydney</strong><span class="date last-meta">October 26, 2016</span></div>
            </div></a></div>
      </div> -->
    </div>
  </div>
  <div class="copyrights">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2017. All rights reserved. The Literary Circle, NIT Durgapur</p>
        </div>
        <div class="col-md-6 text-right">
    <!--      <p>Template By <a href="https://bootstrapious.com/p/bootstrap-carousel" class="text-white">Bootstrapious</a>
            <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
    <!--      </p> -->
        </div>
      </div>
    </div>
  </div>
</footer>

templates/head.html
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bootstrap Blog - B4 Template by Bootstrap Temple</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">

    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />

    <link href='{% static "styles/github.css" %}' rel="stylesheet">

    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>

templates/header.html
<header class="header">
  <!-- Main Navbar-->
  <nav class="navbar navbar-expand-lg">
    <div class="search-area">
      <div class="search-area-inner d-flex align-items-center justify-content-center">
        <div class="close-btn"><i class="icon-close"></i></div>
        <div class="row d-flex justify-content-center">
        </div>
      </div>
    </div>
    <div class="container">
      <!-- Navbar Brand -->
      <div class="navbar-header d-flex align-items-center justify-content-between">
        <!-- Navbar Brand --><a href="index.html" class="navbar-brand">The Darkest White</a>
        <!-- Toggle Button-->
        <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
      </div>
      <!-- Navbar Menu -->
      <div id="navbarcollapse" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><a href="/" class="nav-link ">Home</a>
          </li>
          <li class="nav-item"><a href="/blog" class="nav-link active ">Blog</a>
          </li>
          <li class="nav-item"><a href="#" class="nav-link ">Meet The Team!</a>
          </li>
        </ul>

      </div>
    </div>
  </nav>
</header>

templates/post.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8">
          <div class="container">
            <div class="post-single">
              <div class="post-thumbnail"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="category">
                  {% for cat in post.categories.all %}
                    <a href="{{ cat.get_absolute_url }}">{{ cat }}</a>
                  {% endfor %}
                  </div>
                </div>
                <h1>{{ post.title }}<a href="#"><i class="fa fa-bookmark-o"></i></a></h1>
                <div class="post-footer d-flex align-items-center flex-column flex-sm-row"><a href="#" class="author d-flex align-items-center flex-wrap">
                  <div class="title"><span>{{ post.author }}</span></div></a>
                  <div class="d-flex align-items-center flex-wrap">
                    <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                  </div>
                </div>
                <div class="post-body">
                  {{ post.content | safe }}
                </div>
                <div class="post-tags">
                {% for tag in post.tags.all %}
                <a href="{{ tag.get_absolute_url }}" class="tag">{{ tag.title }}</a>
                {% endfor %}
                </div>
                <div class="posts-nav d-flex justify-content-between align-items-stretch flex-column flex-md-row">
                 {% if post.get_previous_by_timestamp %}
                  <a href="{{ post.get_previous_by_timestamp.get_absolute_url }}" class="prev-post text-left d-flex align-items-center">
                    <div class="icon prev"><i class="fa fa-angle-left"></i></div>
                    <div class="text"><strong class="text-primary">Previous Post </strong>
                      <h6>{{ post.get_previous_by_timestamp.title }}</h6>
                    </div>
                  {% endif %}
                  {% if post.get_next_by_timestamp %}
                  </a><a href="{{ post.get_next_by_timestamp.get_absolute_url }}" class="next-post text-right d-flex align-items-center justify-content-end">
                    <div class="text"><strong class="text-primary">Next Post </strong>
                      <h6>{{ post.get_next_by_timestamp.title }}</h6>
                    </div>
                    <div class="icon next"><i class="fa fa-angle-right">   </i></div></a></div>
                  {% endif %}
              </div>
            </div>
          </div>
        </main>
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="{% url 'search' %}" class="search-form">
              <div class="form-group">
                <input type="text" name="q" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
            <div class="blog-posts">
              {% for post in most_recent %}
              <a href="{{ post.get_absolute_url }}">
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ post.title }}</strong>
                    <div class="d-flex align-items-center">
                    </div>
                  </div>
                </div></a>
              {% endfor %}
          </div>
          </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">Categories</h3>
            </header>
            {% for cat in category_count %}
            <div class="item d-flex justify-content-between"><a href="#">{{ cat.categories__title}}</a><span>{{ cat.categories__title__count }}</span></div>
            {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
        <!--  <div class="widget tags">
            <header>
              <h3 class="h6">Tags</h3>
            </header>
            <ul class="list-inline">
              <li class="list-inline-item"><a href="#" class="tag">#Business</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Technology</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Fashion</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Sports</a></li>
              <li class="list-inline-item"><a href="#" class="tag">#Economy</a></li>
            </ul>
          </div> -->
        </aside>
      </div>
    </div>

{% endblock content %}

templates/scripts.html
{% load static %}
<!-- JavaScript files-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
<script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>

<script src='{% static "js/highlight.pack.js" %}'></script>
<script>hljs.initHighlightingOnLoad();</script>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>